openapi: 3.1.0
info:
  version: 1.0.0
  title: Simple contacts App
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Very simple minimalistic contacts app.
tags:
  - name: Contacts
    description: Operation with contacts.
  - name: Auth
    description: Auth operations.

servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-5-0ts0.onrender.com
paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/postRegister.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/postLogin.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/postLogout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/postRefresh.yaml
  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/postSend-reset-email.yaml
  /auth/reset-pwd:
    post:
      $ref: ../swagger/paths/auth/postReset-pwd.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
